name: Web - Build and Commit

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./platforms/web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: yarn install

      - name: Run build command
        run: yarn build

      # Move build output to the repo root
      - name: Move build output to home directory
        run: |
          rm -rf ../../build
          mv build ../../build

      - name: Commit and push code changes
        working-directory: ./   # go back to repo root
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: Update build [skip ci]" || echo "No changes to commit"
          git push
